
[info.refine_pts]

text = """\r
HEMATITE                +1  pt
IRON                    +2  pts
HIGH-PURITY IRON        +6  pts
DAMASCUS ORE            +2  pts
DAMASCUS STEEL          +4  pts
HIGH-PURITY DAMASCUS    +12 pts
MITHRIL ORE             +4  pts
HIGH-PURITY MITHRIL     +24 pts
ORICHALCUM ORE          +8  pts
ORICHALCUM              +16 pts
HIGH-PURITY ORICHALCUM  +48 pts


150 pts = 1% success rate
"""


[info.trait_farm_locations]

text = """\r
https://youtube.com/watch?v=9XbpGQMSKWw&si=WR1H5lCCyzJZGoD_
"""


[info.summer_event_guide_by_lies]


text = """\r
SUMMER GUIDE FOR BENINGGINERS (Made by Lies)

Need luk chars full luk is enough to farm mana and drop rates
shells can be farm on spots

 
-lutaros cavern for low lvl luk farmers Below 10khp mobs good for  low lvl luk chars

-ultimea sewer south mid high lvl need luk 7-9k dmg for 1 hit

-shrine of the gods area1 bubble angel( blue) stable farm 1 spot need same 7-9k ig

-high lvl farm be on algid passage and can farm all materials in 1 place need 30k+ storm or cyclone dmg for 1 hit 

 . . . .  . . . . .. . 
DIVING GUIDE BY LIES 

NEED FULL LUK CHAR DROP BOOKS
THE MORE DROPbooks or luk the higher point 

-buy max arrows and buffs from  npc on beachhouse ull see  naman 

- diving order kill pusit >then lionfish >then spam killing sharks when they spawn
then boss octopus appears must kill tentacles for higher points 


AMEN
"""



[info.status_calculator_links]

text = """\r
Innuo's Sheet - https://docs.google.com/spreadsheets/d/1JMuTE00mtVuE5bfmvngiMjt73Sy892nTBlO0gLdNOqE/edit?usp=drivesdk
Coryn Stat Calculator - https://coryn.club/stat_calculator.php
"""


[info.blacksmith_prof_leveling]

text = """\r
Full TEC Blacksmiths proficiency guide
Showing the Full TEC BS Proficiency Levelling guide.
Prof Lvl: 0 - 13
Item: Adventurer's Garb
Prof Lvl: 13 - 140
Item: Lightning Bolt Spear
Prof Lvl: 140 - 170
Item: Red Spider Lily | Jade Lance
Prof Lvl: 170 - 185
Item: Bark Mail | Dragon Slayer | Arachnid Sword | Arachnid Claws
Prof Lvl: 185 - 200
Item: Dragon Slayer | Arachnid Sword | Arachnid Claws | Aeria Spada | Reaper Bow
Prof Lvl: 200 - 210
Item: Aeria Spada | Reaper Bow | Rock Dragon Bracers
Prof Lvl: 210 - 220
Item: Vermio Bow | Vegitos Bowgun | Sharp Baghnakhs | Nero Saber | Maiden
Prof Lvl: 220 - 230
Item: Trickstar Costume | Pholidota Blade | Pholidota Shield | Ocean Bowgun | Light Trident | Seapent Bow | Sphere Staff | Orbital Mystic Spheres | Assassin Blade | Carbon Lance | Sacred Axe | Prayer Cross | Savage Bow | Sharp Edge Spear
Prof Lvl: 230 - 240
Item: Trickster Costume | Carbon Lance | Sacred Axe | Prayer Cross | Cursed Gun | Erde Sword | Nacht Staff | Savage Bow | Sharp Edge Spear
Prof Lvl: 240 - 250
Item: Trickster Costume | Savage Bow | Sharp Edge Spear
Prof Lvl: 250 - 265
Item: Water Priest Robe | Amnis Rapier | Amnis Staff | Abyss Katana | Abyss Bow | Avid Glaive | Avid Blade
Prof Lvl: 265 - 275
Item: Abyss Katana | Abyss Bow | Avid Glaive | Avid Blade | Humida Barrel | Humida Wings | Gloomy Flower Staff | Mulgoon Robe
Prof Lvl: 275 - 285
Item: Gloomy Flower Staff | Mulgoon Robe | Anguish Sword | Anguish Knuckles

credits: Toram Xensei
"""